# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: indietech.rocks
description: > # this means to ignore newlines until "baseurl:"
  Listing of products / projects / technologies that don't screw you.
  Please help us expand it. Submit Git pull requests at
  https://github.com/indietechrocks/indietech.rocks
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://indietech.rocks" # the base hostname & protocol for your site
twitter_username: indietechrocks
github_username:  indietechrocks

# Build settings
markdown: kramdown

theme: jekyll-theme-architect

